### ISSUE TITLE
The plugin doesn't support latest Gradle settings

### ISSUE THREAD

**Issue by calmog** [CadisRaziel/plugin_wifi_connect#117]
I'm getting the following error after following the steps at https://flutter.dev/go/flutter-gradle-plugin-apply:

```
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':plugin_wifi_connect' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```

**Comment by chenrilima** [comment]
dependence bot just update a lot of things now, can you check again?

**Comment by ved0** [comment]
The issue still the issue still persists. I am also getting this:

```
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':plugin_wifi_connect' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```

I dont know, it feels like in pub.dev it references to the **old** project. Because there I found version 1.3.50, and it is consistent with the error message, hence the conclusion. I hope it helps.
https://github.com/weplenish/flutter_wifi_connect/blob/main/android/build.gradle

Here you have updated it (this project):
https://github.com/CadisRaziel/plugin_wifi_connect/blob/main/android/build.gradle

**Comment by CadisRaziel** [comment]
@ved0 
The original project was kind of 'abandoned' and we had to pick it up to use it in our company, due to the lack of time due to the sprints we are not able to maintain a consistency of correction.
Ours is more up-to-date thanks to the help of a collaborator who added a bot to update the dependencies automatically.

**Comment by CadisRaziel** [comment]
@ved0 
The original project was kind of 'abandoned' and we had to pick it up to use it in our company, due to the lack of time due to the sprints we are not able to maintain a consistency of correction.
Ours is more up-to-date thanks to the help of a collaborator who added a bot to update the dependencies automatically.

**Comment by CadisRaziel** [comment]
@ved0 
The original project was kind of 'abandoned' and we asked the owner of the repository for permission to take it over and fix the problems that our company needed, but due to the lack of time because of the sprints we are not able to maintain a constant fix for new users.
Ours is more up-to-date thanks to the help of a collaborator who added a bot to update the dependencies automatically.

**Comment by ved0** [comment]
@CadisRaziel 
Yeah, I read about that. And I am using your up-to-date one in my project. I add it into my project with, `flutter pub add plugin_wifi_connect` . And I write some code with it, but when I try to run it. I get this message:
```
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':plugin_wifi_connect' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```

That is why I thougt maybe something got mixed up with the old project. Do you have any suggestions what could be wrong?

**Comment by CadisRaziel** [comment]
@ved0 
Go into the android folder and access build.gradle and you'll see a string called `ext.kotlin_version`, try manually changing the version to `1.5.20` in your project.

if you can't find this build.gradle in vscode, look for the string `ext.kotlin_version` in the magnifying glass.

**Comment by CadisRaziel** [comment]
@ved0 
Go into the android folder and access build.gradle and you'll see a string called `ext.kotlin_version`, try manually changing the version to `1.5.20` in your project.

if you can't find this build.gradle in vscode, look for the string `ext.kotlin_version` in the magnifying glass.

after doing this give your project a full reload

**Comment by calmog** [comment]
@CadisRaziel 
Do you mean to update the string within the plugin_wifi_connect dependency? 
The latest version on pub.dev is currently using ext.kotlin_version = '1.3.50'.

**Comment by CadisRaziel** [comment]
@calmog 
Not so far.
Because there are people who still use the old one, if you want to update you can manually change the version in your project.

**Comment by CadisRaziel** [comment]
@calmog 
Not yet
Because some people still use the old version.
If you want to update, you can manually change the version in your project.

**Comment by calmog** [comment]
You mean within the dependency? Or just copy paste the lib to my project?On 13 May 2024, at 3:33, Vitor Brussolo Zerbato ***@***.***> wrote:﻿
@calmog
Not yet
Because some people still use the old version.
If you want to update, you can manually change the version in your project.

**Comment by CadisRaziel** [comment]
@calmog 
ext.kotlin_version belongs to your created project, check its version, if it is 1.3.50 change it to the desired version 1.5.20, see if it works.

Be careful because if you have other very old libs in your project, there may be a version conflict.

**Comment by CadisRaziel** [comment]
@calmog 
the latest version of ext.kotlin_version if I'm not mistaken is 1.9.0. I can't remember now if it came with the updated dart.

**Comment by calmog** [comment]
I’m using 1.9.20

**Comment by ved0** [comment]
> @calmog Not yet Because some people still use the old version. If you want to update, you can manually change the version in your project.

this worked, thanks :)

**Comment by juan-tado** [comment]
@CadisRaziel @ved0 

Just so I'm clear, you are suggesting to manually modify the source code of `plugin_wifi_connect` locally? 

Cause that can work as a test, but it's not a long term solution since we can't ask every team member to do that. Also wouldn't work in our CI server which will always pull the source code of the dependencies from pub.dev.

Could you publish an updated version with just this change? People that need to stay in the previous version can always lock their version in their `pubspec.yaml` to `1.0.2`.

Would you take a PR with these changes? I'd prefer not to have to maintain a fork just for this.

Thanks

**Comment by CadisRaziel** [comment]
@juan-tado 

No, my friend, you don't understand.
In your project flutter in the build.gradle file (android > build.gradle) when you open this file you will find the global variable `ext.kotlin_version` of your project and not of my extension.

You can modify it directly in your global project, my extension will just follow the new version it needs.

The `ext.kotlin_version` variable is just to define the version of kotlin in your project, it can be modified 

I don't want to change it because I use it in my project and old members also use it in their projects that are already in the play store and app store.

If you have a better solution than updating it for everyone, I'd be willing to implement it.

**Comment by CadisRaziel** [comment]
@juan-tado 
I'll update the version

**Comment by chenrilima** [comment]
> > @calmog Not yet Because some people still use the old version. If you want to update, you can manually change the version in your project.
> 
> this worked, thanks :)

we will update directly in source code. :)

**Comment by DonnyDevIT** [comment]
Im using this fork that fixes for me https://github.com/tadodotcom/plugin_wifi_connect

**Comment by chenrilima** [comment]
> Im using this fork that fixes for me https://github.com/tadodotcom/plugin_wifi_connect

nice!
